config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/step-by-step-pages", status: 302)

  namespace :coronavirus do
    resources :pages,
              path: "",
              only: %i[index show],
              param: :slug do
      get "discard", on: :member
      post "publish", to: "pages#publish", on: :member

      get "edit-header", to: "pages#edit_header"
      patch "edit-header", to: "pages#update_header"

      resources :sub_sections do
        collection do
          get "reorder", to: "reorder_sub_sections#index"
          put "reorder", to: "reorder_sub_sections#update"
        end
      end
    end
  end

  resources :step_by_step_pages, path: "step-by-step-pages" do
    get "approve-2i-review", to: "review#show_approve_2i_review_form"
    post "approve-2i-review", to: "review#approve_2i_review"
    post :check_links
    post "claim-2i-review", to: "review#claim_2i_review"
    get :guidance
    get "internal-change-notes"
    post "internal-change-notes", to: "internal_change_notes#create"
    get "navigation-rules", to: "navigation_rules#edit"
    put "navigation-rules", to: "navigation_rules#update"
    get :publish
    post :publish
    get :publish_without_2i_review
    post :publish_without_2i_review
    get :reorder
    post :reorder
    get "request-change-2i-review", to: "review#show_request_change_2i_review_form"
    post "request-change-2i-review", to: "review#request_change_2i_review"
    post :revert
    post "revert-to-draft", to: "review#revert_to_draft"
    get :schedule
    post :schedule
    post "schedule-datetime"
    get "submit-for-2i", to: "review#submit_for_2i"
    post "submit-for-2i", to: "review#submit_for_2i"
    get :unpublish
    post :unpublish
    post :unschedule

    resources :secondary_content_links, path: "secondary-content-links"
    resources :steps
  end

  resources :mainstream_browse_pages, path: "mainstream-browse-pages",
                                      except: :destroy do
    member do
      post :publish
      get :propose_archive
      post :archive
      get :"manage-child-ordering"
      patch :update_child_ordering
    end
  end

  resources :topics, path: "specialist-sector-pages", except: :destroy do
    member do
      post :publish
      get :propose_archive
      post :archive
    end
  end

  resources :tags, only: [] do
    get :manage_list_ordering
    patch :update_list_ordering

    resources :lists, only: %i[new edit create update destroy show] do
      member do
        get :confirm_destroy
        get :edit_list_items
        patch :update_list_items
        get :manage_list_item_ordering
        patch :update_list_item_ordering
      end

      resources :list_items, only: %i[destroy] do
        member do
          get :confirm_destroy
          get :move
          patch :update_move
        end
      end
    end
  end

  # Legacy route, may have been bookmarked by user.
  get "/topics/:tag_id/lists", to: redirect { |params, _request|
    "/tags/#{params[:tag_id]}/lists"
  }

  post "/link_report", to: "link_report#update"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::ActiveRecord,
    GovukHealthcheck::SidekiqRedis,
  )

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  require "sidekiq/web"
  mount Sidekiq::Web,
        at: "/sidekiq",
        constraints: lambda { |request|
          user = request.env["warden"].user
          user && user.has_permission?("Sidekiq Monitoring")
        }
end

app/models/topic.rb
class Topic < Tag
  has_many :mainstream_browse_pages, through: :reverse_tag_associations, source: :from_tag

  alias_method :subtopic?, :has_parent?

  def base_path
    "/topic/#{full_slug}"
  end

  def subroutes
    return [] unless subtopic?

    %w[/latest]
  end

  def dependent_tags
    if has_parent?
      [parent]
    else
      []
    end
  end

  def can_be_archived?
    published? && !has_active_children?
  end

  def can_be_removed?
    draft? && children.empty?
  end

  def can_have_email_subscriptions?
    level_two?
  end

  def subscriber_list_search_attributes
    { "links" => { topics: [content_id] } }
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :require_gds_editor_permissions!, except: %i[index show]
  before_action :protect_archived_tags!, only: %i[edit update publish]

  def index
    @topics = Topic.sorted_level_one
  end

  def show
    @topic = find_topic
    render "archived_topic" if @topic.archived?
  end

  def edit
    @topic = find_topic
  end

  def update
    topic = find_topic

    if topic.update(topic_params)
      TagBroadcaster.broadcast(topic)
      redirect_to topic, success: "Specialist topic updated"
    else
      @topic = topic
      render "edit"
    end
  end

  def new
    @topic = Topic.new(parent_id: params[:parent_id])
  end

  def create
    topic = Topic.new
    topic.attributes = topic_params

    if topic.save
      TagBroadcaster.broadcast(topic)
      redirect_to topic
    else
      @topic = topic
      render :new
    end
  end

  # Change the topic from draft to published state
  def publish
    topic = find_topic
    TagPublisher.new(topic).publish
    redirect_to topic
  end

  def propose_archive
    @archival = TopicArchivalForm.new(tag: find_topic)
  end

  def archive
    @archival = TopicArchivalForm.new(topic_archival_form_params)
    @archival.tag = find_topic

    if @archival.archive_or_remove
      redirect_to topics_path, success: "The specialist topic has been archived or removed."
    else
      render "propose_archive"
    end
  end

private

  def topic_params
    params.require(:topic).permit(:slug, :title, :description, :parent_id)
  end

  def topic_archival_form_params
    params
      .fetch(:topic_archival_form, {})
      .permit(:tag, :successor, :successor_path)
  end

  def find_topic
    @find_topic ||= Topic.find_by!(content_id: params[:id])
  end

  def protect_archived_tags!
    topic = find_topic
    if topic.archived?
      flash[:alert] = "You cannot modify an archived specialist topic."
      redirect_to topic
    end
  end
end

app/views/topics/_create_update_form.html.erb
<%= form_for @topic do |f| %>
  <% unless update %>
    <div class="govuk-!-margin-bottom-4">
      <%= render "govuk_publishing_components/components/select", {
        id: "topic_parent_id",
        name: "topic[parent_id]",
        label: "Parent (optional)",
        options: Topic.sorted_level_one
                  .map { |topic| {text: topic.title, value: topic.id, selected: topic.id == f.object.parent_id} }
                  .prepend( { text: "", value: "" } )
      } %>
    </div>
  <% end %>

  <%= render "govuk_publishing_components/components/input", {
    label: {
      text: update ? "Slug (read only)" : "Slug"
    },
    id: "topic_slug",
    hint: update ? nil : "For example: lower-case-hyphen-separated",
    readonly: update,
    name: "topic[slug]",
    value: @topic.slug,
    error_items: errors_for(@topic, :slug)
  } %>

  <%= render "govuk_publishing_components/components/input", {
    label: {
      text: "Title"
    },
    id: "topic_title",
    name: "topic[title]",
    value: @topic.title,
    error_items: errors_for(@topic, :title)
  } %>

  <%= render "govuk_publishing_components/components/input", {
    label: {
      text: "Description"
    },
    id: "topic_description",
    name: "topic[description]",
    hint: "This description will be displayed in the search results",
    value: @topic.description,
    error_items: errors_for(@topic, :description)
  } %>

  <%= render "govuk_publishing_components/components/button", {
    text: update ? "Save" : "Create",
    margin_bottom: true
  } %>
<% end %>

app/views/topics/archived_topic.html.erb
<%= render 'shared/breadcrumbs', {
  links: [
    {
      text: 'Specialist topic pages',
      href: topics_url
    },
    *([
      text: @topic.parent[:title],
      href: topic_url(@topic.parent)
    ] if @topic.parent.present? ),
    {
      text: @topic[:title],
    }
  ]
} %>

<% content_for :title, govuk_tag_heading(tag: @topic) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-three-quarters">
    <p class="govuk-body">
      This specialist topic has been archived.
    </p>

    <%= render 'shared/redirects', redirect_routes: @topic.redirect_routes %>

    <% if @topic.children.any? %>
      <section class="govuk-!-margin-bottom-3">
        <%= render "shared/list-children-pages", page: @topic %>
      </section>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<%= render 'shared/breadcrumbs', {
  links: [
    {
      text: 'Specialist topic pages',
      href: topics_url
    },
    *([
      text: @topic.parent[:title],
      href: topic_url(@topic.parent)
    ] if @topic.parent.present? ),
    {
      text: @topic[:title].present? ? @topic[:title] : "Topic",
      href: topic_url(@topic)
    },
    {
      text: 'Edit',
    }
  ]
} %>

<% content_for :title, govuk_tag_heading(tag: @topic, prepend: 'Edit') %>

<%= render 'shared/error_summary', object: @topic %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "create_update_form", update: true %>
  </div>
</div>

app/views/topics/index.html.erb
<% content_for :title, "Specialist topic pages" %>

<% if gds_editor? %>
  <% content_for :title_side, render("govuk_publishing_components/components/button", {
    text: "Add a specialist topic page",
    href: new_topic_path,
    margin_bottom: true
  }) %>
<% end %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-full">
    <p class="govuk-body govuk-!-margin-bottom-3"><%= pluralize(@topics.count, "specialist topic") %></p>
    <%= render "shared/list-browse-pages", pages: @topics %>
  </div>
</div>

app/views/topics/new.html.erb
<%= render 'shared/breadcrumbs', {
  links: [
    {
      text: 'Specialist topic pages',
      href: topics_url
    },
    {
      text: 'New',
    }
  ]
} %>

<% content_for :title, "New specialist topic page" %>

<%= render 'shared/error_summary', object: @topic %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "create_update_form", update: false %>
  </div>
</div>

app/views/topics/propose_archive.html.erb
<%= render 'shared/breadcrumbs', {
  links: [
    {
      text: 'Specialist topic pages',
      href: topics_url
    },
    *([
      text: @archival.tag.parent[:title],
      href: topic_url(@archival.tag.parent)
    ] if @archival.tag.parent.present? ),
    {
      text: @archival.tag[:title],
      href: topic_url(@archival.tag)
    },
    {
      text: 'Archive',
    }
  ]
} %>

<%= govuk_tag_heading(tag: @archival.tag, append: 'Archive specialist topic page') %>

<%= render 'shared/error_summary', object: @archival %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <p class="govuk-body">
      Users who signed up to get emails for this topic will be sent an email that this topic has been archived.
    </p>
    
    <%= form_for @archival, url: archive_topic_path do |f| %>
      <div class="govuk-!-margin-bottom-4">
        <%= render "govuk_publishing_components/components/select", {
          id: "topic_archival_form_successor",
          name: "topic_archival_form[successor]",
          label: "Choose a specialist topic to redirect to:",
          options: @archival.topics.map do |topic|
            {
              text: topic.title_including_parent,
              value: topic.id
            }
          end
        } %>
      </div>

      <%= render "govuk_publishing_components/components/button", {
        text: "Archive and redirect to a specialist topic",
        margin_bottom: true,
        destructive: true,
      } %>
    <% end %>

    <%= form_for @archival, url: archive_topic_path do |f| %>
      <%= render "govuk_publishing_components/components/input", {
        label: {
          text: "Or type in a URL to redirect to a page:"
        },
        hint: 'Please specify it as a relative path (for example "/government/publications/what-hmrc-does-to-prevent-tax-evasion")',
        id: "topic_archival_form_successor_path",
        name: "topic_archival_form[successor_path]",
        error_items: errors_for(@archival, :successor_path)
      } %>

      <%= render "govuk_publishing_components/components/button", {
        text: "Archive and redirect to a page",
        margin_bottom: true,
        destructive: true,
      } %>
    <% end %>
  </div>
</div>

app/views/topics/show.html.erb
<%= render 'shared/breadcrumbs', {
  links: [
    {
      text: 'Specialist topic pages',
      href: topics_url
    },
    *([
      text: @topic.parent[:title],
      href: topic_url(@topic.parent)
    ] if @topic.parent.present? ),
    {
      text: @topic[:title]
    }
  ]
} %>

<% content_for :title, govuk_heading_with_parent(@topic) %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <section class="govuk-!-margin-bottom-3">
      <%= render "govuk_publishing_components/components/summary_list", {
        borderless: true,
        title: "Content",
        items: [
          {
            field: "URL",
            value: link_to(@topic.base_path, Plek.website_root + @topic.base_path, target: "_blank", class: "govuk-link")
          },
          *([
            field: "Parent",
            value: link_to(@topic.parent[:title], topic_url(@topic.parent), class: "govuk-link")
          ] if @topic.parent.present? ),
          {
            field: "Description",
            value: @topic[:description].present? ? @topic[:description] : "Empty"
          },
          {
            field: "Status",
            value: govuk_status(@topic)
          },
        ],
        edit: {
          href: edit_topic_path(@topic),
          link_text: "Edit page"
        }
      } %>
    </section>

    <% if @topic.can_have_children? %>
      <section class="govuk-!-margin-bottom-3">
        <%= render "shared/list-children-pages", page: @topic %>
      </section>
    <% end %>

    <% if @topic.level_two? %>
      <section class="govuk-!-margin-bottom-3">
        <%= render 'shared/list-links-preview', tag: @topic %>
      </section>
    <% end %>
  </div>

  <div class="govuk-grid-column-one-third">
    <aside class="app-side__wrapper">
      <div class="app-side">
        <div class="app-side__actions">
          <% if @topic.may_publish? %>
            <div class="govuk-!-margin-bottom-1">
              <%= form_for @topic, url: publish_topic_path(@topic), method: :post do |form| %>
                <%= render("govuk_publishing_components/components/button", {
                  text: "Publish"
                }) %>
              <% end %>
            </div>
          <% end %>
          <% if @topic.can_have_children? %>
            <div class="govuk-!-margin-bottom-1">
              <% if gds_editor? %>
                <%= link_to "Add subtopic page",
                  new_polymorphic_path(@topic, parent_id: @topic.id),
                  class: %w(govuk-link govuk-link--no-visited-state) %>
              <% end %>
            </div>
          <% end %>
          <div class="govuk-!-margin-bottom-1">
            <% if @topic.can_be_archived? %>
              <%= link_to 'Archive specialist topic page',
                propose_archive_topic_path(@topic),
                class: %w(govuk-link govuk-link--no-visited-state)
              %>
            <% end %>
            <% if @topic.can_be_removed? %>
              <%= link_to 'Delete', archive_topic_path(@topic),
                method: 'post',
                data: { confirm: 'Are you sure?' },
                class: %w(govuk-link app-link--destructive)
              %>
            <% end %>
          </div>
        </div>
      </div>
    </aside>
  </div>
</div>