config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/step-by-step-pages", status: 302)

  namespace :coronavirus do
    resources :pages,
              path: "",
              only: %i[index show],
              param: :slug do
      get "discard", on: :member
      post "publish", to: "pages#publish", on: :member

      get "edit-header", to: "pages#edit_header"
      patch "edit-header", to: "pages#update_header"

      resources :sub_sections do
        collection do
          get "reorder", to: "reorder_sub_sections#index"
          put "reorder", to: "reorder_sub_sections#update"
        end
      end
    end
  end

  resources :step_by_step_pages, path: "step-by-step-pages" do
    get "approve-2i-review", to: "review#show_approve_2i_review_form"
    post "approve-2i-review", to: "review#approve_2i_review"
    post :check_links
    post "claim-2i-review", to: "review#claim_2i_review"
    get :guidance
    get "internal-change-notes"
    post "internal-change-notes", to: "internal_change_notes#create"
    get "navigation-rules", to: "navigation_rules#edit"
    put "navigation-rules", to: "navigation_rules#update"
    get :publish
    post :publish
    get :publish_without_2i_review
    post :publish_without_2i_review
    get :reorder
    post :reorder
    get "request-change-2i-review", to: "review#show_request_change_2i_review_form"
    post "request-change-2i-review", to: "review#request_change_2i_review"
    post :revert
    post "revert-to-draft", to: "review#revert_to_draft"
    get :schedule
    post :schedule
    post "schedule-datetime"
    get "submit-for-2i", to: "review#submit_for_2i"
    post "submit-for-2i", to: "review#submit_for_2i"
    get :unpublish
    post :unpublish
    post :unschedule

    resources :secondary_content_links, path: "secondary-content-links"
    resources :steps
  end

  resources :mainstream_browse_pages, path: "mainstream-browse-pages",
                                      except: :destroy do
    member do
      post :publish
      get :propose_archive
      post :archive
      get :"manage-child-ordering"
      patch :update_child_ordering
    end
  end

  resources :topics, path: "specialist-sector-pages", except: :destroy do
    member do
      post :publish
      get :propose_archive
      post :archive
    end
  end

  resources :tags, only: [] do
    get :manage_list_ordering
    patch :update_list_ordering

    resources :lists, only: %i[new edit create update destroy show] do
      member do
        get :confirm_destroy
        get :edit_list_items
        patch :update_list_items
        get :manage_list_item_ordering
        patch :update_list_item_ordering
      end

      resources :list_items, only: %i[destroy] do
        member do
          get :confirm_destroy
          get :move
          patch :update_move
        end
      end
    end
  end

  # Legacy route, may have been bookmarked by user.
  get "/topics/:tag_id/lists", to: redirect { |params, _request|
    "/tags/#{params[:tag_id]}/lists"
  }

  post "/link_report", to: "link_report#update"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::ActiveRecord,
    GovukHealthcheck::SidekiqRedis,
  )

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  require "sidekiq/web"
  mount Sidekiq::Web,
        at: "/sidekiq",
        constraints: lambda { |request|
          user = request.env["warden"].user
          user && user.has_permission?("Sidekiq Monitoring")
        }
end

app/models/step_by_step_page.rb
class StepByStepPage < ApplicationRecord
  STATUSES = %w[
    draft
    submitted_for_2i
    in_review
    approved_2i
    scheduled
    published
  ].freeze

  has_many :navigation_rules, -> { order(title: :asc) }, dependent: :destroy
  has_many :steps, -> { order(position: :asc) }, dependent: :destroy
  has_many :internal_change_notes, -> { order(created_at: :desc) }
  has_many :secondary_content_links, -> { order(title: :asc) }, dependent: :destroy

  belongs_to :reviewer, primary_key: "uid", class_name: "User", optional: true
  belongs_to :review_requester, primary_key: "uid", class_name: "User", optional: true

  validates :title, :slug, :introduction, :description, presence: true
  validates :scheduled_at, in_future: true
  validates :slug, format: { with: /\A([a-z0-9]+-)*[a-z0-9]+\z/ }, uniqueness: { case_sensitive: false }
  validates :slug, slug: true, on: :create
  validates :status, inclusion: { in: STATUSES }, presence: true
  validates :status, status_prerequisite: true
  validate :reviewer_is_not_same_as_review_requester

  before_validation :strip_slug_spaces
  before_destroy :discard_notes

  scope :by_title, -> { order(:title) }

  attribute :content_id, :string, default: -> { SecureRandom.uuid }
  attribute :auth_bypass_id, :string, default: -> { SecureRandom.uuid }

  def has_been_published?
    published_at.present?
  end

  def has_draft?
    draft_updated_at.present? && draft_updated_at != published_at
  end

  def scheduled_for_publishing?
    status.scheduled?
  end

  def mark_draft_updated
    update(
      draft_updated_at: Time.zone.now,
      status: "draft",
    )
  end

  def mark_draft_deleted
    update(draft_updated_at: nil)
  end

  def mark_as_approved_2i
    self.status = "approved_2i"
    save!(validate: false)
  end

  def mark_as_published
    now = Time.zone.now
    update!(
      published_at: now,
      draft_updated_at: now,
      scheduled_at: nil,
      assigned_to: nil,
      review_requester_id: nil,
      reviewer_id: nil,
      status: "published",
    )
  end

  def mark_as_unpublished
    update(
      published_at: nil,
      draft_updated_at: Time.zone.now,
      status: "approved_2i",
    )
  end

  def mark_as_scheduled
    update(status: "scheduled")
  end

  def mark_as_unscheduled
    update(status: "approved_2i", scheduled_at: nil)
  end

  def refresh_auth_bypass_id
    update(auth_bypass_id: SecureRandom.uuid)
  end

  def self.validate_redirect(redirect_url)
    regex = /\A\/[\/.a-zA-Z0-9-]*\z/
    regex.match?(redirect_url)
  end

  def status
    (self["status"] || "").inquiry
  end

  def unpublished_changes?
    has_draft? && has_been_published?
  end

  def can_be_published?
    has_draft? &&
      !scheduled_for_publishing? &&
      steps_have_content? &&
      links_checked_since_last_update? &&
      status.approved_2i?
  end

  def can_be_unpublished?
    has_been_published? && !scheduled_for_publishing?
  end

  def can_discard_changes?
    unpublished_changes? && !scheduled_for_publishing?
  end

  def can_be_deleted?
    !has_been_published? && !scheduled_for_publishing?
  end

  def can_be_edited?
    !scheduled_for_publishing?
  end

  def steps_have_content?
    steps.any? && steps.map(&:contents).all?(&:present?)
  end

  def links_last_checked_date
    steps.map(&:links_last_checked_date).reject(&:blank?).max
  end

  def should_show_required_prepublish_actions?
    (has_draft? && !scheduled_for_publishing? && !can_be_published?) || status.in_review?
  end

  def links_checked_since_last_update?
    (links_checked? && links_last_checked_date > draft_updated_at) || status.approved_2i?
  end

  def links_checked?
    steps.map(&:link_report?).any?
  end

  def discard_notes
    internal_change_notes.where(edition_number: nil).delete_all
  end

  def make_step_positions_sequential
    steps.sort_by(&:position).each.with_index(1) do |step, index|
      step.update!(position: index)
    end
  end

private

  def strip_slug_spaces
    slug.gsub!(/^\s+|\s+$/, "")
  end

  def reviewer_is_not_same_as_review_requester
    if review_requester_id.present? && review_requester_id == reviewer_id
      errors.add(:reviewer_id, "can't be the same as review_requester_id")
    end
  end
end

app/controllers/step_by_step_pages_controller.rb
class StepByStepPagesController < ApplicationController
  include PublishingApiHelper
  include TimeOptionsHelper

  before_action :require_gds_editor_permissions!
  before_action :set_step_by_step_page, only: %i[show edit update destroy]
  before_action :require_to_be_2i_approved, only: %i[publish schedule schedule_datetime]
  before_action :require_skip_review_permissions!, only: %i[publish_without_2i_review]

  def index
    @step_by_step_pages = StepByStepFilter::Results.new(filter_params).call
  end

  def new
    @step_by_step_page = StepByStepPage.new
  end

  def show
    @step_by_step_page_presenter = StepByStepPagePresenter.new(@step_by_step_page)
  end

  def reorder
    set_current_page_as_step_by_step
    if request.post? && params.key?(:step_order_save)
      reordered_steps = @step_by_step_page.steps.sort_by do |step|
        params.require(:step_order_save).fetch(step.id.to_s, step.position).to_i
      end

      reordered_steps.each.with_index(1) do |step, index|
        step.update!(position: index)
      end

      StepByStepUpdater.call(@step_by_step_page, current_user)
      redirect_to @step_by_step_page, notice: "Steps were successfully reordered."
    end
  end

  def edit; end

  def create
    create_params = step_by_step_page_params.merge(status: "draft")
    @step_by_step_page = StepByStepPage.new(create_params)
    if @step_by_step_page.save
      StepByStepUpdater.call(@step_by_step_page, current_user)
      redirect_to @step_by_step_page, notice: "Step by step page was successfully created."
    else
      render :new
    end
  end

  def update
    if @step_by_step_page.update(step_by_step_page_params)
      StepByStepUpdater.call(@step_by_step_page, current_user)
      redirect_to step_by_step_page_path, notice: "Step by step page was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    if @step_by_step_page.destroy
      discard_draft
      redirect_to step_by_step_pages_path, notice: "Step by step page was successfully deleted."
    else
      render :edit
    end
  end

  def publish
    set_current_page_as_step_by_step
    if request.post?
      @publish_intent = PublishIntent.new(publish_intent_params)
      if @publish_intent.valid?
        publish_page(@publish_intent)
        generate_internal_change_note("Published", publish_note_description)
        set_change_note_version
        redirect_to @step_by_step_page, notice: "'#{@step_by_step_page.title}' has been published."
      end
    end
  end

  def publish_without_2i_review
    set_current_page_as_step_by_step
    if request.post?
      @publish_intent = PublishIntent.new(publish_intent_params)
      if @publish_intent.valid?
        publish_page(@publish_intent)
        generate_internal_change_note("Published without 2i review", publish_note_description)
        set_change_note_version
        send_publish_without_2i_email
        redirect_to @step_by_step_page, notice: "'#{@step_by_step_page.title}' has been published."
      end
    else
      render :publish
    end
  end

  def schedule
    set_current_page_as_step_by_step
  end

  def schedule_datetime
    set_current_page_as_step_by_step
    if params[:schedule]
      date_params = params[:schedule][:date].permit(:year, :month, :day).to_h.symbolize_keys
      time_param = params[:schedule][:time]
      @schedule_placeholder = default_datetime_placeholder(**date_params.merge(time: time_param))
      @parser = DatetimeParser.new(date: date_params, time: time_param)
      scheduled_at = @parser.parse
      if @parser.issues.any?
        @parser.issues.each do |issue|
          @step_by_step_page.errors.add :base, issue.values.first
        end
        render :schedule_datetime
      elsif @step_by_step_page.update(scheduled_at:)
        schedule_to_publish(session[:update_type], session[:public_change_note])
        note_headline = "Scheduled to publish"
        note_description = "Scheduled at #{format_full_date_and_time(scheduled_at)}"
        note_description << " with change note: #{session[:public_change_note]}" if session[:public_change_note].present?
        generate_internal_change_note(note_headline, note_description)
        set_change_note_version
        redirect_to @step_by_step_page, notice: "'#{@step_by_step_page.title}' has been scheduled to publish."
      end
    else
      @schedule_placeholder = default_datetime_placeholder
      session[:update_type] = params[:update_type]
      session[:public_change_note] = params[:change_note]
    end
  end

  def unpublish
    set_current_page_as_step_by_step
    if request.post?
      redirect_url = params.delete("redirect_url")
      if StepByStepPage.validate_redirect(redirect_url)
        unpublish_page(redirect_url)
        redirect_to @step_by_step_page, notice: "Step by step page was successfully unpublished."
      else
        flash[:alert] = "Redirect path is invalid. Step by step page has not been unpublished."
      end
    end
  end

  def unschedule
    set_current_page_as_step_by_step
    unschedule_publishing
    note_headline = "Scheduled publishing stopped"
    generate_internal_change_note(note_headline)
    set_change_note_version
    redirect_to @step_by_step_page, notice: "Publishing of '#{@step_by_step_page.title}' has been unscheduled."
  end

  def revert
    set_current_page_as_step_by_step
    if request.post?
      discard_draft
      revert_page
      generate_internal_change_note("Draft discarded")
      redirect_to @step_by_step_page, notice: "Draft successfully discarded."
    else
      render :edit
    end
  end

  def check_links
    set_current_page_as_step_by_step
    @step_by_step_page.steps.each(&:request_broken_links)
    redirect_to @step_by_step_page, notice: "Links are currently being checked. Please refresh the page to check progress. When all links have been checked, you'll see a message below each step."
  end

  def internal_change_notes
    set_current_page_as_step_by_step
    @internal_change_note = InternalChangeNote.new
  end

  helper_method :issues_for
  def issues_for(namespace)
    return if @parser.nil?

    @parser.issues_for(namespace).map { |error| { text: error } }
  end

  def guidance
    set_current_page_as_step_by_step
    render :guidance
  end

private

  def discard_draft
    @step_by_step_page.discard_notes
    StepNavPublisher.discard_draft(@step_by_step_page)
  rescue GdsApi::HTTPNotFound
    Rails.logger.info "Discarding #{@step_by_step_page.content_id} failed"
  end

  def publish_intent_params
    @step_by_step_page.has_been_published? ? params : { update_type: "minor" }
  end

  def publish_page(publish_intent)
    StepNavPublisher.update_draft(@step_by_step_page, publish_intent)
    StepNavPublisher.publish(@step_by_step_page)
    @step_by_step_page.mark_as_published
  end

  def schedule_to_publish(update_type, change_note)
    publish_intent = PublishIntent.new(update_type:, change_note:)
    StepNavPublisher.schedule_for_publishing(@step_by_step_page)
    StepNavPublisher.update_draft(@step_by_step_page, publish_intent)
    @step_by_step_page.mark_as_scheduled
  end

  def unpublish_page(redirect_url)
    begin
      StepNavPublisher.unpublish(@step_by_step_page, redirect_url)
    rescue GdsApi::HTTPNotFound
      Rails.logger.info "Unpublishing #{@step_by_step_page.content_id} failed"
    end
    @step_by_step_page.mark_as_unpublished
    generate_internal_change_note("Unpublished")
  end

  def unschedule_publishing
    StepNavPublisher.cancel_scheduling(@step_by_step_page)
    @step_by_step_page.mark_as_unscheduled
  end

  def revert_page
    published_version = latest_edition_number(@step_by_step_page.content_id, publication_state: "published")
    payload = Services.publishing_api.get_content(@step_by_step_page.content_id, version: published_version).to_hash

    StepByStepPageReverter.new(@step_by_step_page, payload).repopulate_from_publishing_api
  end

  def publish_note_description
    "With change note: #{@publish_intent.change_note}" unless @publish_intent.change_note.empty?
  end

  def generate_internal_change_note(note_headline, note_description = nil)
    change_note = @step_by_step_page.internal_change_notes.new(
      author: current_user.name,
      headline: note_headline,
      description: note_description,
    )
    change_note.save!
  end

  def set_change_note_version
    change_notes = @step_by_step_page.internal_change_notes.where(edition_number: nil)
    change_notes.update_all(edition_number: latest_edition_number(@step_by_step_page.content_id))
  end

  def set_step_by_step_page
    @step_by_step_page = StepByStepPage.find(params[:id])
  end

  def step_by_step_page_params
    params.require(:step_by_step_page).permit(:title, :slug, :introduction, :description)
  end

  def filter_params
    params.permit(:title_or_url, :status, :order_by)
  end

  def set_current_page_as_step_by_step
    @step_by_step_page = StepByStepPage.find(params[:step_by_step_page_id])
  end

  def require_to_be_2i_approved
    set_current_page_as_step_by_step
    unless @step_by_step_page.status.approved_2i?
      redirect_to @step_by_step_page, notice: "Step by step must be 2i approved before you can #{action_name} this step by step."
    end
  end

  def send_publish_without_2i_email
    PublisherNotifications.publish_without_2i(@step_by_step_page, current_user).deliver_now
  end
end

app/views/step_by_step_pages/_change_notes.html.erb
<% textarea = capture do %>
    <%= render "govuk_publishing_components/components/textarea", {
      label: {
        text: t("step_by_step_pages.change_notes.label"),
      },
      name: "change_note",
      rows: 4,
      hint: t("step_by_step_pages.change_notes.hint"),
    } %>
<% end %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds" id="change-note">
    <%= render "govuk_publishing_components/components/radio", {
      heading: t("step_by_step_pages.change_notes.title"),
      heading_size: "s",
      name: "update_type",
      id: "update-type",
      items: [
        {
          value: "major",
          text: "Yes",
          conditional: textarea,
        },
        {
          value: "minor",
          text: "No",
          checked: true,
        }
      ]
    } %>
  </div>
</div>

app/views/step_by_step_pages/_nav.html.erb
<%
  active ||= ''
%>

<%= render "components/tabs", {
  tabs: [
    {
      href: @step_by_step_page,
      label: "Summary",
      active: active == 'edit-steps'
    },
    {
      href: step_by_step_page_internal_change_notes_path(@step_by_step_page),
      label: "History",
      active: active == 'internal-change-notes'
    }
  ]
} %>

app/views/step_by_step_pages/internal_change_notes.html.erb
<%
  links = [
    {
      text: 'Step by steps',
      href: step_by_step_pages_path
    },
    {
      text: @step_by_step_page.title,
      href: @step_by_step_page
    },
    {
      text: 'History'
    }
  ]
%>

<% content_for :breadcrumbs, render('shared/steps/step_breadcrumb', links: links) %>
<% content_for :title, @step_by_step_page.title %>
<% content_for :context, 'Step by step' %>

<%= render 'nav', step_by_step_page: @step_by_step_page, active: "internal-change-notes" %>

<%= form_for(@internal_change_note, url: step_by_step_page_internal_change_notes_path) do |form| %>
  <%= render "shared/steps/form_errors", resource: @step_by_step_page %>
  <%= render "govuk_publishing_components/components/contextual_guidance", {
    html_for: "internal-change-note-description",
    title: t("step_by_step_pages.internal_change_notes.label"),
    content: t("step_by_step_pages.internal_change_notes.guidance")
  } do %>
    <%= render "govuk_publishing_components/components/textarea", {
      label: {
        text: t("step_by_step_pages.internal_change_notes.label"),
        bold: true
      },
      id: "internal-change-note-description",
      name: "internal_change_note[description]"
    } %>
  <% end %>

  <%= render "govuk_publishing_components/components/button", {
    text: "Add internal note",
    margin_bottom: true
  } %>
<% end %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render "govuk_publishing_components/components/accordion", {
      items: @step_by_step_page.internal_change_notes
        .group_by { |edition| edition.edition_number }
        .map { |_ , records|
          {
            heading: {
              text: sanitize("#{records.first.edition_number ? "#{records.first.edition_number.to_i.ordinalize} edition" : "Current version"}")
            },
            content: {
              html: sanitize(records.map { |note|
                  "<div class='app-c-internal-change-note'>
                    <h4 class='app-c-internal-change-note__headline'>#{note.headline}</h4>
                    <p class='app-c-internal-change-note__timestamp'>#{note.readable_created_date} by #{note.author}</p>
                    <pre class='app-c-internal-change-note__description'>#{note.description}</pre>
                  </div>"
                }.join
              )
            },
            expanded: !records.first.edition_number
          }
        }
    } %>
  </div>
</div>

app/views/step_by_step_pages/reorder.html.erb
<%
  links = [
    {
      text: 'Step by steps',
      href: step_by_step_pages_path
    },
    {
      text: @step_by_step_page.title,
      href: step_by_step_page_path(@step_by_step_page)
    },
    {
      text: 'Reorder steps'
    }
  ]
%>

<% content_for :breadcrumbs, render('shared/steps/step_breadcrumb', links: links) %>
<% content_for :title, @step_by_step_page.title %>
<% content_for :context, "Reorder steps" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= render_markdown t("step_by_step_pages.reorder.instructions_markdown") %>
    <%= render_markdown t("step_by_step_pages.reorder.automatically_updated_markdown") %>

    <%
      step_number = 1
      steps = @step_by_step_page.steps.map do |step|
        if step.logic == 'number'
          prefix = step_number
          step_number += 1
        else
          prefix = step.logic
        end

        { id: step.id, title: "#{prefix} - #{step.title}" }
      end
    %>

    <% if steps.length > 0 %>
      <%= form_for(@step_by_step_page, url: step_by_step_page_reorder_path(@step_by_step_page), method: :post) do |form| %>
        <%= render 'govuk_publishing_components/components/reorderable_list', {
          input_name: "step_order_save",
          items: steps,
        } %>

        <div class="govuk-grid-row">
          <div class="govuk-grid-column-full">
            <%= render "govuk_publishing_components/components/button", {
              text: "Save"
            } %>
          </div>
          <div class="govuk-grid-column-full govuk-!-margin-top-3">
            <%= link_to 'Cancel', @step_by_step_page, class: "govuk-link" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="govuk-body"><strong>There are currently no steps to display.</strong></p>
      <%= link_to 'Cancel', @step_by_step_page, class: "govuk-link" %>
    <% end %>
  </div>
</div>

app/views/step_by_step_pages/schedule.html.erb
<%
  links = [
    {
      text: 'Step by steps',
      href: step_by_step_pages_path
    },
    {
      text: @step_by_step_page.title,
      href: step_by_step_page_path(@step_by_step_page)
    },
    {
      text: 'Schedule publish'
    }
  ]
%>

<% content_for :breadcrumbs, render('shared/steps/step_breadcrumb', links: links) %>
<% content_for :title, @step_by_step_page.title %>
<% content_for :context, "Schedule publish" %>

<% if @step_by_step_page.errors.any? %>
  <%= render "shared/steps/form_errors", resource: @step_by_step_page %>
<% end %>

<%= form_tag(step_by_step_page_schedule_datetime_path(@step_by_step_page)) do %>
  <%= render "step_by_step_pages/change_notes" %>

  <%= render "govuk_publishing_components/components/button", {
    text: "Continue",
    margin_bottom: true
  } %>

  <%= tag.p link_to("Cancel", @step_by_step_page, class: "govuk-link"), class: "govuk-body" %>
<% end %>

app/views/step_by_step_pages/secondary_links.html.erb
<%
  links = [
    {
      text: 'Step by step publisher',
      href: step_by_step_pages_path
    },
    {
      text: @step_by_step_page.title,
      href: step_by_step_page_path(@step_by_step_page)
    },
    {
      text: 'Secondary links'
    }
  ]
%>

<%= render 'shared/steps/step_breadcrumb', links: links %>

<%= render 'shared/steps/heading',
  step_nav: @step_by_step_page.title,
  action: 'Secondary links'
%>

<%= render 'nav', step_by_step_page: @step_by_step_page, active:"secondary-links" %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
          What is secondary content?
        </h3>
      </div>
      <div class="panel-body">
        <p>Secondary content is content which is not linked to in the step by step, but has the step by step sidebar showing on it.</p>
        <p>We use it for content which:
          <ul>
            <li>helps you to complete a task in the journey, but is not the primary piece of content you need to visit to complete that task</li>
            <li>is optional and not useful enough to be included in the step by step</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@secondary_links, url: step_by_step_page_secondary_links_path) do |form| %>
      <%= render "shared/steps/form_errors", resource: @step_by_step_page %>

      <details class="add-secondary-link--details">
        <summary class="add-secondary-link--summary">
          <span class="btn btn-primary">Add a secondary link</span>
        </summary>
        <div class="form-group">
          <label for="link">Link</label>
          <input type="text" name="link" required="true" class="form-control add-secondary-link--input">
          <p class="add-secondary-link__exampleText">For example: <a href="https://www.gov.uk/pay-vat">https://www.gov.uk/pay-vat</a> or <a href="https://www.gov.uk/bank-holidays">/bank-holidays</a></p>
          <%= form.submit "Add secondary link", class: "btn btn-success" %>
          <a href="<%= step_by_step_page_secondary_links_path %>" class="btn btn-link add-secondary-link-cancel--link">Cancel</a>
        </div>
      </details>
    <% end %>
  </div>
</div>

<hr />

<div class="row secondary-links">
  <div class="col-md-12">
    <h2>Existing secondary links</h2>
    <table class="table table-striped table-stepnav-rules" data-module="filterable-table">
    <thead>
      <tr>
        <th colspan="3">
        <div class='filter-control'>
          <%= render partial: 'govuk_admin_template/table_filter_form', locals: { placeholder: 'Search for a rule here' } %>
        </div>
        </th>
      </tr>
      <tr>
        <th>Page title</th>
        <th>Path</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @step_by_step_page.navigation_rules.each do |navigation_rule| %>
        <tr>
          <td><%= link_to(navigation_rule.title, preview_url(navigation_rule.base_path)) %></td>
          <td><%= navigation_rule.base_path %></td>
          <td>
            <%= link_to("Delete", "/fdsds", method: 'delete', data: { confirm: "Are you sure?" }, class: "btn btn-danger btn-sm") %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/step_by_step_pages/unpublish.html.erb
<%
  links = [
    {
      text: 'Step by steps',
      href: step_by_step_pages_path
    },
    {
      text: @step_by_step_page.title,
      href: @step_by_step_page
    },
    {
      text: 'Unpublish'
    }
  ]
%>

<% content_for :breadcrumbs, render('shared/steps/step_breadcrumb', links: links) %>
<% content_for :title, @step_by_step_page.title %>
<% content_for :context, "Unpublish" %>

<%= render "govuk_publishing_components/components/error_alert", {
  message: "Warning",
  description: "You are unpublishing a page from GOV.UK. This can’t be undone."
} %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_tag(step_by_step_page_unpublish_path(@step_by_step_page), method: :post) do %>
      <h3 class="govuk-heading-m">Unpublish</h3>

      <%= render "govuk_publishing_components/components/input", {
        label: {
          text: "Redirect to"
        },
        name: :redirect_url,
        hint: sanitize("For example: <code>/redirect-to-replacement-page</code>")
      } %>

      <div class="form-group">
        <%= render "govuk_publishing_components/components/button", {
          text: "Unpublish",
          data_attributes: {
            module: "confirm",
            message: "This will remove ‘#{@step_by_step_page.title}’ from the website.\n\n Are you sure?"
          },
          destructive: true
        } %>
      </div>
    <% end %>
  </div>
</div>