config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/step-by-step-pages", status: 302)

  namespace :coronavirus do
    resources :pages,
              path: "",
              only: %i[index show],
              param: :slug do
      get "discard", on: :member
      post "publish", to: "pages#publish", on: :member

      get "edit-header", to: "pages#edit_header"
      patch "edit-header", to: "pages#update_header"

      resources :sub_sections do
        collection do
          get "reorder", to: "reorder_sub_sections#index"
          put "reorder", to: "reorder_sub_sections#update"
        end
      end
    end
  end

  resources :step_by_step_pages, path: "step-by-step-pages" do
    get "approve-2i-review", to: "review#show_approve_2i_review_form"
    post "approve-2i-review", to: "review#approve_2i_review"
    post :check_links
    post "claim-2i-review", to: "review#claim_2i_review"
    get :guidance
    get "internal-change-notes"
    post "internal-change-notes", to: "internal_change_notes#create"
    get "navigation-rules", to: "navigation_rules#edit"
    put "navigation-rules", to: "navigation_rules#update"
    get :publish
    post :publish
    get :publish_without_2i_review
    post :publish_without_2i_review
    get :reorder
    post :reorder
    get "request-change-2i-review", to: "review#show_request_change_2i_review_form"
    post "request-change-2i-review", to: "review#request_change_2i_review"
    post :revert
    post "revert-to-draft", to: "review#revert_to_draft"
    get :schedule
    post :schedule
    post "schedule-datetime"
    get "submit-for-2i", to: "review#submit_for_2i"
    post "submit-for-2i", to: "review#submit_for_2i"
    get :unpublish
    post :unpublish
    post :unschedule

    resources :secondary_content_links, path: "secondary-content-links"
    resources :steps
  end

  resources :mainstream_browse_pages, path: "mainstream-browse-pages",
                                      except: :destroy do
    member do
      post :publish
      get :propose_archive
      post :archive
      get :"manage-child-ordering"
      patch :update_child_ordering
    end
  end

  resources :topics, path: "specialist-sector-pages", except: :destroy do
    member do
      post :publish
      get :propose_archive
      post :archive
    end
  end

  resources :tags, only: [] do
    get :manage_list_ordering
    patch :update_list_ordering

    resources :lists, only: %i[new edit create update destroy show] do
      member do
        get :confirm_destroy
        get :edit_list_items
        patch :update_list_items
        get :manage_list_item_ordering
        patch :update_list_item_ordering
      end

      resources :list_items, only: %i[destroy] do
        member do
          get :confirm_destroy
          get :move
          patch :update_move
        end
      end
    end
  end

  # Legacy route, may have been bookmarked by user.
  get "/topics/:tag_id/lists", to: redirect { |params, _request|
    "/tags/#{params[:tag_id]}/lists"
  }

  post "/link_report", to: "link_report#update"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::ActiveRecord,
    GovukHealthcheck::SidekiqRedis,
  )

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  require "sidekiq/web"
  mount Sidekiq::Web,
        at: "/sidekiq",
        constraints: lambda { |request|
          user = request.env["warden"].user
          user && user.has_permission?("Sidekiq Monitoring")
        }
end

app/models/navigation_rule.rb
class NavigationRule < ApplicationRecord
  belongs_to :step_by_step_page

  validates :title, :base_path, :content_id, :step_by_step_page_id, :publishing_app, :schema_name, presence: true

  scope :part_of_content_ids, -> { where(include_in_links: "always").pluck(:content_id) }
  scope :related_content_ids, -> { where(include_in_links: "conditionally").pluck(:content_id) }

  def smartanswer?
    schema_name == "smart_answer" || (schema_name == "transaction" && publishing_app == "smartanswers")
  end

  def display_text(value)
    {
      "always" => "Always show navigation",
      "conditionally" => "Show navigation if user comes from a step-by-step",
      "never" => "Never show navigation",
    }[value]
  end
end

app/controllers/navigation_rules_controller.rb
class NavigationRulesController < ApplicationController
  before_action :require_gds_editor_permissions!
  before_action :set_step_by_step_page, only: %i[edit update]

  def edit
    @step_by_step_page.navigation_rules
  end

  def update
    navigation_rules = params.delete(:navigation_rules)

    navigation_rules.each_pair do |content_id, value|
      value = %w[always conditionally never].include?(value) ? value : "always"

      rule = @step_by_step_page.navigation_rules.find_by(content_id:)
      rule.update!(include_in_links: value) if rule
    end

    StepByStepDraftUpdateWorker.perform_async(@step_by_step_page.id)

    redirect_to(@step_by_step_page, notice: "Your navigation choices have been saved.")
  end

private

  def set_step_by_step_page
    @step_by_step_page = StepByStepPage.find(params[:step_by_step_page_id])
  end
end

app/views/navigation_rules/edit.html.erb
<%
  links = [
    {
      text: 'Step by steps',
      href: step_by_step_pages_path
    },
    {
      text: @step_by_step_page.title,
      href: step_by_step_page_path(@step_by_step_page)
    },
    {
      text: 'Sidebar settings',
    }
  ]
%>

<% content_for :breadcrumbs, render('shared/steps/step_breadcrumb', links: links) %>
<% content_for :title, @step_by_step_page.title %>
<% content_for :context, 'Sidebar settings' %>

<%= render 'shared/steps/form_notice', message: notice, status: "success" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds govuk-!-margin-bottom-6">
    <h3 class="govuk-heading-m"><%= t("sidebar_settings.header") %></h3>
    <p class="govuk-body"><%= render_markdown t("guidance.sidebar_settings.guidance_markdown") %></p>
  </div>
</div>

<div class="govuk-grid-row">
  <%= form_for(step_by_step_page_navigation_rules_path(@step_by_step_page), method: :put) do |form| %>
    <div class="govuk-grid-column-full">
      <table class="govuk-table table-stepnav-rules">
        <thead class="govuk-table__head">
          <tr>
            <th class="govuk-table__header" scope="col">Page title</th>
            <th class="govuk-table__header" scope="col">Path</th>
            <th class="govuk-table__header" scope="col">Sidebar content of page</th>
          </tr>
        </thead>

        <tbody class="govuk-table__body">
          <% if @step_by_step_page.navigation_rules.present? %>
            <% @step_by_step_page.navigation_rules.each do |navigation_rule| %>
              <tr class="govuk-table__row">
                <td class="govuk-table__cell"><%= link_to(navigation_rule.title, draft_govuk_url(navigation_rule.base_path), class: "govuk-link") %></td>
                <td class="govuk-table__cell"><%= navigation_rule.base_path %></td>
                <td class="govuk-table__cell">
                  <% if @step_by_step_page.can_be_edited? %>
                    <%= render "govuk_publishing_components/components/select", {
                      id: "navigation_rules[#{navigation_rule.content_id}]",
                      label: "",
                      options: [
                        {
                          text: navigation_rule.display_text("always"),
                          value: "always",
                          selected: true
                        },
                        {
                          text: navigation_rule.display_text("conditionally"),
                          value: "conditionally",
                        },
                        {
                          text: navigation_rule.display_text("never"),
                          value: "never"
                        }
                      ].each{ |item| item[:selected] = item[:value] == navigation_rule.include_in_links }
                    } %>
                  <% else %>
                    <%= tag.p navigation_rule.display_text(navigation_rule.include_in_links), id: "navigation_rules[#{navigation_rule.content_id}]" %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          <% else %>
            <tr class="govuk-table__row">
              <td class="govuk-table__cell" colspan="3">
                <p class="govuk-hint">No links exist</p>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% if @step_by_step_page.navigation_rules.present? && @step_by_step_page.can_be_edited?%>
      <%= render "govuk_publishing_components/components/button", {
        text: "Save"
      } %>
    <% end %>
  <% end %>
</div>