config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/step-by-step-pages", status: 302)

  namespace :coronavirus do
    resources :pages,
              path: "",
              only: %i[index show],
              param: :slug do
      get "discard", on: :member
      post "publish", to: "pages#publish", on: :member

      get "edit-header", to: "pages#edit_header"
      patch "edit-header", to: "pages#update_header"

      resources :sub_sections do
        collection do
          get "reorder", to: "reorder_sub_sections#index"
          put "reorder", to: "reorder_sub_sections#update"
        end
      end
    end
  end

  resources :step_by_step_pages, path: "step-by-step-pages" do
    get "approve-2i-review", to: "review#show_approve_2i_review_form"
    post "approve-2i-review", to: "review#approve_2i_review"
    post :check_links
    post "claim-2i-review", to: "review#claim_2i_review"
    get :guidance
    get "internal-change-notes"
    post "internal-change-notes", to: "internal_change_notes#create"
    get "navigation-rules", to: "navigation_rules#edit"
    put "navigation-rules", to: "navigation_rules#update"
    get :publish
    post :publish
    get :publish_without_2i_review
    post :publish_without_2i_review
    get :reorder
    post :reorder
    get "request-change-2i-review", to: "review#show_request_change_2i_review_form"
    post "request-change-2i-review", to: "review#request_change_2i_review"
    post :revert
    post "revert-to-draft", to: "review#revert_to_draft"
    get :schedule
    post :schedule
    post "schedule-datetime"
    get "submit-for-2i", to: "review#submit_for_2i"
    post "submit-for-2i", to: "review#submit_for_2i"
    get :unpublish
    post :unpublish
    post :unschedule

    resources :secondary_content_links, path: "secondary-content-links"
    resources :steps
  end

  resources :mainstream_browse_pages, path: "mainstream-browse-pages",
                                      except: :destroy do
    member do
      post :publish
      get :propose_archive
      post :archive
      get :"manage-child-ordering"
      patch :update_child_ordering
    end
  end

  resources :topics, path: "specialist-sector-pages", except: :destroy do
    member do
      post :publish
      get :propose_archive
      post :archive
    end
  end

  resources :tags, only: [] do
    get :manage_list_ordering
    patch :update_list_ordering

    resources :lists, only: %i[new edit create update destroy show] do
      member do
        get :confirm_destroy
        get :edit_list_items
        patch :update_list_items
        get :manage_list_item_ordering
        patch :update_list_item_ordering
      end

      resources :list_items, only: %i[destroy] do
        member do
          get :confirm_destroy
          get :move
          patch :update_move
        end
      end
    end
  end

  # Legacy route, may have been bookmarked by user.
  get "/topics/:tag_id/lists", to: redirect { |params, _request|
    "/tags/#{params[:tag_id]}/lists"
  }

  post "/link_report", to: "link_report#update"

  get "/healthcheck/live", to: proc { [200, {}, %w[OK]] }
  get "/healthcheck/ready", to: GovukHealthcheck.rack_response(
    GovukHealthcheck::ActiveRecord,
    GovukHealthcheck::SidekiqRedis,
  )

  mount GovukPublishingComponents::Engine, at: "/component-guide"

  require "sidekiq/web"
  mount Sidekiq::Web,
        at: "/sidekiq",
        constraints: lambda { |request|
          user = request.env["warden"].user
          user && user.has_permission?("Sidekiq Monitoring")
        }
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :list

  validates :index, numericality: { greater_than_or_equal_to: 0 }

  scope :ordered, -> { order(:index) }

  attr_accessor :tagged
  alias_method :tagged?, :tagged

  def display_title
    list.tag.tagged_document_for_base_path(base_path).try(:title) || title
  end

  def content_id
    list.tag.tagged_document_for_base_path(base_path).content_id
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :find_tag
  before_action :find_list
  before_action :find_list_item
  before_action :require_gds_editor_permissions_to_edit_browse_pages!

  def destroy
    @list_item.destroy!
    ListPublisher.new(@tag).perform
    flash[:notice] = "#{@list_item.title} removed from list"

    redirect_to tag_list_path(@tag, @list)
  end

  def confirm_destroy; end

  def move; end

  def update_move
    @list_item.errors.add(:new_list_id, "Choose a list") if move_list_item_params.blank?
    render :move and return if @list_item.errors.present?

    new_list = @tag.lists.find(move_list_item_params)
    new_index = new_list.list_items.map(&:index).max.to_i + 1
    @list_item.update!(list: new_list, index: new_index)
    ListPublisher.new(@tag).perform
    flash[:notice] = "#{@list_item.title} moved to #{new_list.name} successfully"

    redirect_to tag_list_path(@tag, @list)
  end

private

  def find_list
    @list = @tag.lists.find(params[:list_id])
  end

  def find_list_item
    @list_item = @list.list_items.find(params[:id])
  end

  def list_item_params
    params.require(:list_item).permit(:title, :base_path, :index)
  end

  def move_list_item_params
    params.dig(:list_item, :new_list_id)
  end
end

app/views/list_items/confirm_destroy.html.erb
<%= content_for :back_link, render("govuk_publishing_components/components/back_link", {
  href: tag_list_path(@tag, @list)
}) %>

<%= content_for :context, "List" %>

<% content_for :title, "Confirm removal of link" %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_for @list_item, url: tag_list_list_item_path(@tag, @list, @list_item), method: :delete do |f| %>
      <p class="govuk-body">Are you sure you want to delete "<%= @list_item.title %>"?</p>

      <%= render "govuk_publishing_components/components/button", {
        text: "Remove link",
        destructive: true,
      } %>
    <% end %>
  </div>
</div>

app/views/list_items/move.html.erb
<%= content_for :back_link, render("govuk_publishing_components/components/back_link", {
  href: tag_list_path(@tag, @list)
}) %>

<%= content_for :page_title, "Move link to a different list" %>

<%= render 'shared/error_summary', object: @list_item %>

<div class="govuk-grid-row">
  <div class="govuk-grid-column-two-thirds">
    <%= form_for @list, url: update_move_tag_list_list_item_path(@tag, @list, @list_item), method: :patch do |f| %>
      <%= render "govuk_publishing_components/components/radio", {
        name: "list_item[new_list_id]",
        id: "list_item_new_list_id",
        heading: "Move link to a different list",
        heading_size: "l",
        heading_caption: "List",
        heading_level: 1,
        error_message: errors_for(@list_item, :new_list_id),
        items: @tag.lists_that_do_not_include_list_item(@list_item).map do |list|
        {
          value: list.id,
          text: list.name,
        }
        end
      } %>

      <%= render "govuk_publishing_components/components/button", {
        text: "Next"
      } %>
    <% end %>
  </div>
</div>